version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=gcnra_db
      - POSTGRES_USER=gcnra_user
      - POSTGRES_PASSWORD=gcnra_pass
    ports:
      - "5432:5432"
    restart: always
